feat: [ENG-1848] Consumer group reconnect
clinia/x pull request #74
Opened 2024-12-17 01:25 UTC by pobeaulieu1

Adds mechanism to reconnect consumer group if did not consume messages for a while and there is a lag.

2024-12-17 01:28 UTC, pobeaulieu1 commented on pubsubx/kgox/consumer.go
> +	maxLag = 0
Having a hard time mocking kafka client because of this: https://github.com/twmb/franz-go/issues/58#issuecomment-896368502

2024-12-17 03:40 UTC, pobeaulieu1 commented on pubsubx/kgox/kgo_client.go
> +// KgoClient is an interface that wraps the kgo.Client
This is because kgo.Client is not an interface. Read this form more info on why we cant mock as is: https://github.com/twmb/franz-go/issues/58#issuecomment-896368502

2024-12-17 16:17 UTC, phturb commented on pubsubx/kgox/consumer.go
> +				err = c.Subscribe(context.WithoutCancel(ctx), topicHandlers)
I would not call subscribe again, instead lets store the information from the bootstrap step, then lets have an execute call that we can just loop on.
Here there is too much logic in the defer and we will end up having an infinite recursive stack. Also it will make it a mess with the mutex every time we restart.

2024-12-17 16:17 UTC, phturb commented on pubsubx/kgox/consumer.go
> +			lag := getLag(tp)
I don't think thus will work. IIRC fetches returns only if there is a message that comes in, so if no message comes in we wont reach that point

2024-12-17 16:17 UTC, phturb commented on pubsubx/kgox/kgo_client.go
> +// KgoClient is an interface that wraps the kgo.Client
Question I have here as the issue comment is valid, why do we need to mock it ? Maybe we should look into how the tests are done so that we can test the logic without requiring a mock.

2024-12-17 16:24 UTC, pobeaulieu1 commented on pubsubx/kgox/consumer.go
> +				err = c.Subscribe(context.WithoutCancel(ctx), topicHandlers)
Discussed with Will and we decided to simply close the consumer group in case of lag and timeout and let atlas restart the worker with the Health endpoint.

2024-12-17 16:27 UTC, pobeaulieu1 commented on pubsubx/kgox/consumer.go
> +			lag := getLag(tp)
Correct. Will move the logic in a goroutine and use the admin client to comoute the lag.

2024-12-18 01:47 UTC, pobeaulieu1 commented on pubsubx/kgox/kgo_client.go
> +// KgoClient is an interface that wraps the kgo.Client
Mocking also became a problem when instantiating an admin client. Will need to find a way to unit test this without a mock.

2024-12-18 20:47 UTC, pobeaulieu1 commented on pubsubx/kgox/consumer.go
> +				err = c.Subscribe(context.WithoutCancel(ctx), topicHandlers)
Not applicable anymore. Will let atlas close the consumer group. Health returns an error.

2024-12-18 23:47 UTC, xWiiLLz commented on configx/provider.go
> +			HealthTimeout:   p.DurationF("pubsub.consumerGroupMonitoring.health_timeout", 0),
These should be set to a value, we can't have the enabled flag turned on and a zero value for both the timeout and interval IMO

2024-12-23 15:33 UTC, pobeaulieu1 commented on configx/provider.go
> +			HealthTimeout:   p.DurationF("pubsub.consumerGroupMonitoring.health_timeout", 0),
This is the fallback value if it is not set (duration is int64). We also have this check 
```
func (cgm ConsumerGroupMonitoringConfig) IsEnabled() bool {
	return cgm.Enabled && cgm.HealthTimeout != 0 && cgm.RefreshInterval != 0
}
```

2025-01-07 13:12 UTC, xWiiLLz requested changes
Stuff to rework.

2025-01-07 13:12 UTC, xWiiLLz commented on pubsubx/kgox/consumer.go
> +		}
First, remember that this guard rail was designed to catch very specific networking errors where all of the topics of a consumer group were "stuck".
We would first want all of the topics to be stuck in order to trigger this guard rail. If only one topic is stuck, then the consumer group is still making progress and this guard rail would not be triggered (which is not the case currently).

Furthermore, we need to look at the lag like you did, but also the offsets like we discussed offline. If the lag is non-zero but the offsets are still moving forward, then the consumer group is still making progress and this guard rail should not be triggered.
Here's some pseudo-code to highlight the checks:
```
if each topic has (timeElapsed > healthTimeout && lag > 0 && offset == lastReadOffset) {
    triggerGuardRail();
}
```

There is another edge case we would want to consider. Imagine we have a healthTimeout of 2m, and a last read occured 1m59s ago when all topics were lag free.
If there are messages being pushed to some of the topics at this time and the consumption takes more than 1s to fetch the messages, we would have this guard rail triggered.
To fix this, a dumb solution would be to reset all of the lastConsumptionTimes to the current time in the monitor loop if all of the lags are zero at that time. That way, the timeout would really start only when we are spotting a lag.
Note that this would also need to be guarded by the mutex.

2025-01-07 13:12 UTC, xWiiLLz commented on pubsubx/kgox/consumer.go
> +	groupLags, err := c.adminClient.Lag(ctx, c.group.ConsumerGroup(c.conf.Scope))
What if this call is always failing? We could have a small retry and in case of repeated failure, set the lags to a non-zero value to trigger the guard rail.

2025-01-07 18:31 UTC, pobeaulieu1 commented on configx/provider.go
> +			HealthTimeout:   p.DurationF("pubsub.consumerGroupMonitoring.health_timeout", 0),
setting to 5 min and 5 seconds for now

2025-01-08 01:56 UTC, pobeaulieu1 commented on pubsubx/kgox/consumer.go
> +		}
Good points. You may look at the new version and let me know what you think.

2025-01-08 03:48 UTC, pobeaulieu1 commented on pubsubx/kgox/consumer.go
> +	groupLags, err := c.adminClient.Lag(ctx, c.group.ConsumerGroup(c.conf.Scope))
I implemented the retry mechanism implemented. Instead of setting arbitrary lags, I set c.cancel = nil so that the health endpoint returns an error.

2025-01-10 20:48 UTC, pobeaulieucl commented on pubsubx/kgox/consumer_test.go
> +		kgo.SeedBrokers("localhost:19992", "localhost:29992", "localhost:39992"),
@xWiiLLz Testing with toxiproxy to induce toxics or proxy disable for *Consumers only* without affecting producers will not work considering how redpanda advertises external addresses: 
In our Docker compose, we have: 
```
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092'
```
This means that even though here we are trying to configure a write client that bypasses the proxy, it will still go through it because it will use the advertized address.  

I believe we wont be able to test the condition where the consumer is stuck while the producer still pushes message with toxiproxy.

2025-01-15 21:02 UTC, closed without merging

2025-01-15 21:04 UTC, pobeaulieucl commented
Closing as this was not the source of the problem, refer to: https://github.com/clinia/x/pull/87